// Generated by gencpp from file motion_plan/reference_point.msg
// DO NOT EDIT!


#ifndef MOTION_PLAN_MESSAGE_REFERENCE_POINT_H
#define MOTION_PLAN_MESSAGE_REFERENCE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_plan
{
template <class ContainerAllocator>
struct reference_point_
{
  typedef reference_point_<ContainerAllocator> Type;

  reference_point_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , mode(0)  {
    }
  reference_point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef int16_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::motion_plan::reference_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_plan::reference_point_<ContainerAllocator> const> ConstPtr;

}; // struct reference_point_

typedef ::motion_plan::reference_point_<std::allocator<void> > reference_point;

typedef boost::shared_ptr< ::motion_plan::reference_point > reference_pointPtr;
typedef boost::shared_ptr< ::motion_plan::reference_point const> reference_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_plan::reference_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_plan::reference_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_plan::reference_point_<ContainerAllocator1> & lhs, const ::motion_plan::reference_point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_plan::reference_point_<ContainerAllocator1> & lhs, const ::motion_plan::reference_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motion_plan::reference_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_plan::reference_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_plan::reference_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_plan::reference_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_plan::reference_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_plan::reference_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_plan::reference_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25fe4ce9c6c513804d777b4bfd749dc0";
  }

  static const char* value(const ::motion_plan::reference_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25fe4ce9c6c51380ULL;
  static const uint64_t static_value2 = 0x4d777b4bfd749dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_plan::reference_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_plan/reference_point";
  }

  static const char* value(const ::motion_plan::reference_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_plan::reference_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"int16 mode\n"
;
  }

  static const char* value(const ::motion_plan::reference_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_plan::reference_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reference_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_plan::reference_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_plan::reference_point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLAN_MESSAGE_REFERENCE_POINT_H
